Resources:
  ECRCodeBuildIam:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        -
          PolicyName: "codebuild-golang-nodejs"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action:
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:GetAuthorizationToken"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:PutImage"
                  - "ecr:UploadLayerPart"
                  - "logs:*"
                  - "s3:*"
                Resource: "*"
      RoleName: "codebuild-docker-ecr"
  ECRRepo:
    Type: "AWS::ECR::Repository"
    Properties: 
      RepositoryName: docker-golang-nodejs-repository
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
  ECRDockerCodeBuild:
    Type: "AWS::CodeBuild::Project"
    Properties: 
      Artifacts:
        Type: "NO_ARTIFACTS"
      BadgeEnabled: "true"
      Description: "ECR Codebuild Docker"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/docker:17.09.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          -
            Name: IMAGE_REPO_NAME
            Type: PLAINTEXT
            Value: !Ref ECRRepo
          -
            Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          -
            Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
          -
            Name: IMAGE_TAG
            Type: PLAINTEXT
            Value: latest
      Name: "golang-nodejs-docker"
      ServiceRole: 
        Ref: "ECRCodeBuildIam"
      Source:
        Location: "https://github.com/kkesley/ecr-golang-nodejs"
        Type: "GITHUB"
      Tags:
        - 
          Key: "Name"
          Value: "Golang Nodejs Docker"