Resources:
  ECRCodeBuildIam:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        -
          PolicyName: "ca-api-codebuild-golang"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action:
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:GetAuthorizationToken"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:PutImage"
                  - "ecr:UploadLayerPart"
                  - "logs:*"
                  - "s3:*"
                Resource: "*"
      RoleName: "ca-codebuild-docker-ecr"
  ECRRepo:
    Type: "AWS::ECR::Repository"
    Properties: 
      RepositoryName: docker-golang-nodejs-repository
  ECRDockerCodeBuild:
    Type: "AWS::CodeBuild::Project"
    Properties: 
      Artifacts:
        Type: "NO_ARTIFACTS"
      Description: "ECR Codebuild Docker"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/docker:17.09.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          -
            Name: IMAGE_REPO_NAME
            Type: PLAINTEXT
            Value: !Ref ECRRepo
          -
            Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          -
            Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
          -
            Name: IMAGE_TAG
            Type: PLAINTEXT
            Value: latest
      Name: "ca-golang-nodejs-docker"
      ServiceRole: 
        Ref: "ECRCodeBuildIam"
      Source:
        Location:
          !Join
            - ""
            - - !Ref DockerS3
              - "/DockerGolangNodejsServerless.zip"
        Type: "S3"
      Tags:
        - 
          Key: "Name"
          Value: "CA Golang Nodejs Docker"
  DockerS3:
    Type: "AWS::S3::Bucket"